name: Github Pages
run-name: ${{ github.actor }} 
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Edit editURL [params]
        run: |
          sed -i 's#editURL = ".*"#editURL = \"${{ steps.pages.outputs.base_url }}\"#g' config.toml
          cat config.toml
     
      - name: Build
        run: hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public